#
# Automagically generated by Approximatrix Simply Fortran 3.7
#
FC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\ar.exe"
WRC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\windres.exe"
PRJTK="C:\Program Files (x86)\Simply Fortran 3\fwin\sfprjtk.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\benthic.o": ".\benthic.f95"
	@echo Compiling .\benthic.f95
	@$(FC) -c -o "build\benthic.o" $(FFLAGS) ".\benthic.f95"

"build\grainsize.o": ".\grainsize.f95"
	@echo Compiling .\grainsize.f95
	@$(FC) -c -o "build\grainsize.o" $(FFLAGS) ".\grainsize.f95"

"build\location.o": ".\location.f95"
	@echo Compiling .\location.f95
	@$(FC) -c -o "build\location.o" $(FFLAGS) ".\location.f95"

"build\newsedmain1.o": ".\newsedmain1.f95"
	@echo Compiling .\newsedmain1.f95
	@$(FC) -c -o "build\newsedmain1.o" $(FFLAGS) ".\newsedmain1.f95"

"build\passed.o": ".\passed.f95"
	@echo Compiling .\passed.f95
	@$(FC) -c -o "build\passed.o" $(FFLAGS) ".\passed.f95"

"build\passed1fornewsed1.o": ".\passed1fornewsed1.f95"
	@echo Compiling .\passed1fornewsed1.f95
	@$(FC) -c -o "build\passed1fornewsed1.o" $(FFLAGS) ".\passed1fornewsed1.f95"

"build\sedcount.o": ".\sedcount.f95"
	@echo Compiling .\sedcount.f95
	@$(FC) -c -o "build\sedcount.o" $(FFLAGS) ".\sedcount.f95"

"build\tsf.o": "..\tsf.f95"
	@echo Compiling ..\tsf.f95
	@$(FC) -c -o "build\tsf.o" $(FFLAGS) "..\tsf.f95"

"build\tsf2.o": ".\tsf2.f95"
	@echo Compiling .\tsf2.f95
	@$(FC) -c -o "build\tsf2.o" $(FFLAGS) ".\tsf2.f95"

"build\tsfb.o": ".\tsfb.f95"
	@echo Compiling .\tsfb.f95
	@$(FC) -c -o "build\tsfb.o" $(FFLAGS) ".\tsfb.f95"

"build\watchar.o": "..\watchar.f95"
	@echo Compiling ..\watchar.f95
	@$(FC) -c -o "build\watchar.o" $(FFLAGS) "..\watchar.f95"

clean: .SYMBOLIC
	@echo Deleting build\newsedmain.o and related files
	@$(RM) "build\newsedmain.o"
	@echo Deleting build\analyticalsettling.o and related files
	@$(RM) "build\analyticalsettling.o"
	@echo Deleting build\benthic.o and related files
	@$(RM) "build\benthic.o"
	@echo Deleting build\grainsize.o and related files
	@$(RM) "build\grainsize.o"
	@echo Deleting build\location.o and related files
	@$(RM) "build\location.o"
	@echo Deleting build\newsedmain1.o and related files
	@$(RM) "build\newsedmain1.o"
	@echo Deleting build\passed.o and related files
	@$(RM) "build\passed.o"
	@echo Deleting build\passed1.o and related files
	@$(RM) "build\passed1.o"
	@echo Deleting build\passed1fornewsed1.o and related files
	@$(RM) "build\passed1fornewsed1.o"
	@echo Deleting build\sedcount.o and related files
	@$(RM) "build\sedcount.o"
	@echo Deleting build\tsf.o and related files
	@$(RM) "build\tsf.o"
	@echo Deleting build\tsf2.o and related files
	@$(RM) "build\tsf2.o"
	@echo Deleting build\tsfb.o and related files
	@$(RM) "build\tsfb.o"
	@echo Deleting build\watchar.o and related files
	@$(RM) "build\watchar.o"
	@echo Deleting target.exe
	@$(RM) "target.exe"

"target.exe":  "build\benthic.o" "build\grainsize.o" "build\location.o" "build\newsedmain1.o" "build\passed.o" "build\passed1fornewsed1.o" "build\sedcount.o" "build\tsf.o" "build\tsf2.o" "build\tsfb.o" "build\watchar.o" "build\NewthreelayerSed.prj.target"
	@echo Generating target.exe
	@$(FC) -o "target.exe" -static "build\benthic.o" "build\grainsize.o" "build\location.o" "build\newsedmain1.o" "build\passed.o" "build\passed1fornewsed1.o" "build\sedcount.o" "build\tsf.o" "build\tsf2.o" "build\tsfb.o" "build\watchar.o" $(LDIR) $(PRJ_LFLAGS)

all: "target.exe" .SYMBOLIC

